CREATE DATABASE book_repository;

CREATE SCHEMA book_storage;
DROP SCHEMA book_storage;

CREATE TABLE authors
(
    id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(128) NOT NULL,
    last_name  VARCHAR(128) NOT NULL
);

CREATE TABLE books
(
    id           INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(256) NOT NULL,
    year         INT          NOT NULL,
    pages_amount INT          NOT NULL,
    author_id    INT REFERENCES authors (id) ON DELETE CASCADE
);

DROP TABLE books;
DROP TABLE authors;

INSERT INTO authors (first_name, last_name)
VALUES ('George', 'Orwell'),
       ('Jane', 'Austen'),
       ('J.K.', 'Rowling'),
       ('Ernest', 'Hemingway'),
       ('F. Scott', 'Fitzgerald'),
       ('Agatha', 'Christie');

INSERT INTO books (name, year, pages_amount, author_id)
VALUES ('1984', 1949, 328, 1),
       ('Animal Farm', 1945, 112, 1),
       ('Pride and Prejudice', 1813, 279, 2),
       ('Emma', 1815, 474, 2),
       ('Harry Potter and the Philosopher''s Stone', 1997, 309, 3),
       ('Harry Potter and the Chamber of Secrets', 1998, 341, 3),
       ('The Old Man and the Sea', 1952, 127, 4),
       ('A Farewell to Arms', 1929, 332, 4),
       ('The Great Gatsby', 1925, 180, 5),
       ('Murder on the Orient Express', 1934, 256, 6),
       ('And Then There Were None', 1939, 272, 6);

SELECT name,
       year,
       (SELECT concat(a.last_name, ', ', a.first_name) FROM authors AS a WHERE a.id = author_id)
FROM books
ORDER BY year;



